### PR TITLE
Minor adjustments to components

### LINKED ISSUE #4: Upgrade code quality
I'm not sure how I can improve this but I believe there is room to improve it !

### PR DESCRIPTION
**Pull request by HurricaneInteractive**
There wasn't anything in here that stood out as "wrong". Just small adjustments;

1. Changing class components to function components, kinda indicates that they don't do much + state can always be introduced using [hooks](https://reactjs.org/docs/hooks-intro.html)
2. In the Batasan and Labo components, I'd look at those fetch methods. They seem duplicated and one can be removed from Batasan. I left it in just in case you're still working on it. Look into creating some abstraction methods to reduce duplication. For example

```js
// Helper method
const fetchdata = async (url) => {
  const data = await fetch(url);
  const json = await data.json();
  const arrayOfData = []

  // Do the loop

  return arrayOfData
}

// In component
const value = await fetchdata("<url>")
// Do some more changes to `value` if needed
this.setState({ key: value })
```

Other than that is looks fine. Some other recommendations are including something like [eslint](https://eslint.org/) and [prettier](https://prettier.io/) to keep code style consistent.

Fixes #4

### CODE REVIEW

**Comment by mashiromashi** [comment]
I'm not sure how to enforce eslint to react project, i ended up having errors in the preflight check and uninstall and delete the .eslintrc.json. 
Really want to add that so that it looks a bit better than current style.

**Comment by HurricaneInteractive** [comment]
I'd be happy to look into installing and configing it all to work with your project as another PR?

**Comment by mashiromashi** [comment]
I'll merge this one for now I guess then. If you want to send another PR. It's up to you.

**Comment by HurricaneInteractive** [comment]
Great! Will do, possibly sometime tomorrow.

**Comment by mashiromashi** [comment]
Take your time. No rush. Thanks for helping me out.

**Pull request merged**
